services:
  - type: web
    name: zahlengrafik-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
